### ISSUE TITLE
Count the number of times heuristics are used

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#162]
Can we add to a CSV the number of times a log level is not lowered in a catch block and the number of times a log level is not transformed because of the if condition (we have a log for this per #153). If the setting is off, then the value should be 0.

**Comment by saledouble** [comment]
Example of output (the option for if blocks with log levels is turned on):

sequence | subject | repo URL | input logging statements | passing logging statements | failures | transformed logging statements | average Java lines added | average Java lines removed | log level not lowered in a catch block | log level not transformed due to if condition | use log category (SEVERE/WARNING/CONFIG) | use log category (CONFIG) | not lower log levels of logs inside of catch   blocks | time (s)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1552591817924 | Logging-Level-Evolution-Test | https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 3 | 3 | 0 | 2 | 5 | 0 | 0 | 1 | FALSE | FALSE | FALSE | 0.424
1552591818352 | Logging-Level-Evolution-Test | https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 3 | 3 | 0 | 1 | 0 | 0 | 1 | 1 | FALSE | FALSE | TRUE | 0.263
1552591818616 | Logging-Level-Evolution-Test | https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 3 | 3 | 0 | 2 | 0 | 0 | 0 | 1 | FALSE | TRUE | FALSE | 0.287
1552591818903 | Logging-Level-Evolution-Test | https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 3 | 3 | 0 | 1 | 0 | 0 | 1 | 1 | FALSE | TRUE | TRUE | 0.518
1552591819422 | Logging-Level-Evolution-Test | https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 3 | 3 | 0 | 0 | 0 | 0 | 0 | 1 | TRUE | FALSE | FALSE | 0.851
1552591820273 | Logging-Level-Evolution-Test | https://github.com/ponder-lab/Logging-Level-Evolution-Test.git | 3 | 3 | 0 | 0 | 0 | 0 | 1 | 1 | TRUE | FALSE | TRUE | 0.244

**Comment by saledouble** [comment]
If I turn the setting of `if block` off, the number is 0.

**Comment by khatchad** [comment]
This also needs to be done for #250

**Comment by khatchad** [comment]
As well as any other heuristics that have bee added.

**Comment by saledouble** [comment]
>As well as any other heuristics that have bee added.
OK

**Comment by saledouble** [comment]
>This also needs to be done for #250

I can count the number for it, but I didn't make a setting for this issue like other heuristics. I think I should make it, right?

**Comment by khatchad** [comment]
Yeah it probably should be a setting.

**Comment by saledouble** [comment]
Done. This issue may be reopened if we add more heuristics in the future.
