### ISSUE TITLE
Contradicting N

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#168]
I set N to 300 in `eval.properties`. In [the log](https://github.com/khatchad/Logging-Level-Evolution-Evaluation/blob/master/logs.txt), it says 300. In [`repos.csv`](https://github.com/khatchad/Logging-Level-Evolution-Evaluation/blob/master/repos.csv), it says 100.

**Comment by saledouble** [comment]
Sorry, I cannot reproduce this issue. It works well on my computer.

The default N is 100. It looks like the plugin does not read `eval.properties` on your computer. Are the content of your file like this `NToUseForCommits=300`?

**Comment by khatchad** [comment]
But if it didn't read N from the computer, why would it say in the logs that it is using 300? Furthermore, why would it say that both the actual and N are 100?

**Comment by saledouble** [comment]
Based on logs, you were evaluating a project not in a valid git repo, but its project root file or its ancestors have `eval.properties`. The project roots and the ancestors of the projects you listed in `result.csv` don't have `eval.properties`. Sorry, I cannot get further conclusion without more details.

N is the maximum of evaluated commits, and `actual` is the actual number that our plugin evaluates. `actual` is always smaller or equal to N. Based on `results.csv`, our plugin only evaluated 100 commits due to the limitation of N.

**Comment by khatchad** [comment]
I thought it was the workspace where the file goes.

**Comment by khatchad** [comment]
I think that actual is misnamed. It's really the number processed. Could we also have the number of actual commits in the branch?

**Comment by saledouble** [comment]
>I thought it was the workspace where the file goes.

If your project files are in the workspace and `eval.properties` is in the workspace, the eval file could be detected. The tool finds the eval file at the project root at first, if it cannot be found, the tool will look up its parents recursively.

>I think that actual is misnamed. It's really the number processed. 

OK, I will rename it. 

> Could we also have the number of actual commits in the branch?

Yes, we could.
