### ISSUE TITLE
Average Java lines added and average Java lines removed columns do not change with number of commits processed

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#226]
I would expect to have different numbers for "average Java lines added" and "average Java lines removed" when "number of commits processed" changes. Why are they the same?

https://github.com/ponder-lab/Logging-Level-Evolution-Evaluation/blob/d2927a8eb4611643f5f1a6b53fa8dbb88b49042c/repos.csv:

sequence | repo URL | SHA-1 of head | N for commits | number of commits processed | actual number of commits | average Java lines added | average Java lines removed
-- | -- | -- | -- | -- | -- | -- | --
1557305220769 | https://github.com/bcgit/bc-java.git | d569f4bcf49612a17da482735a48f715e3727150 | 1000 | 1000 | 5561 | 110.978 | 39.414
1557325236532 | https://github.com/bcgit/bc-java.git | d569f4bcf49612a17da482735a48f715e3727150 | 300 | 300 | 5561 | 110.978 | 39.414

**Comment by saledouble** [comment]
Is this CSV file received from one running? I remember we add a loop of number of commits to get this file. The problem is that when we are using a loop to get the data in one running time, the memoization is working. Therefore, when the same project is analyzed, the tool will not compute the average java lines again, and it will use the existing one. For now, we already removed that loop. This issue will not show again.
